
spring:

  application:
    name: jvm

  profiles:
    active: dev

  datasource:
    druid:
      username: root
      password: '123456'
      url: jdbc:mysql://127.0.0.1:3306/huiyou?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5
      maxActive: 20
      minIdle: 2
      maxWait: 60000
      validationQuery: SELECT 1
      validationQueryTimeout: 6000
      testOnBorrow: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 28000
